BackOffice/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Modeles;
using Repositories;
using Services.Service;

namespace BackOffice.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private CategorieService categorieService;

        public CategoriesController()
        {
            this.categorieService = new CategorieService(new ProjetContext());
        }

        // GET: Categories
        public ActionResult Index()
        {
            return View(categorieService.GetCategories());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int id)
        {
            Categorie categorie = categorieService.GetCategorieByID(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Libelle")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                categorieService.InsertCategorie(categorie);
                categorieService.Save();
                return RedirectToAction("Index");
            }

            return View(categorie);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int id)
        {
            Categorie categorie = categorieService.GetCategorieByID(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: Categories/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Libelle")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                categorieService.UpdateCategorie(categorie);
                //categorieService.Save();
                return RedirectToAction("Index");
            }
            return View(categorie);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int id)
        {
            Categorie categorie = categorieService.GetCategorieByID(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            categorieService.DeleteCategorie(id);
            return RedirectToAction("Index");
        }
    }
}

BackOffice/Controllers/InscriptionController.cs
using BackOffice.ViewModels;
using BackOffice.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using Modeles;
using Repositories;
using Services.Service;

namespace BackOffice.Controllers
{
    public class InscriptionController : Controller
    {
        private ProjetContext context = new ProjetContext();
        private UtilisateurService utilisateurService;

        public InscriptionController()
        {
            this.utilisateurService = new UtilisateurService(context);
        }

        // GET: Inscription/Inscription
        public ActionResult Inscription()
        {
            return View();
        }

        // POST: Inscription/Inscription
        [HttpPost]
        public ActionResult Inscription(InscriptionVueModele inscriptionVueModele)
        {
            if(!String.IsNullOrEmpty(inscriptionVueModele.Utilisateur.Mdp) && !String.IsNullOrEmpty(inscriptionVueModele.Mdp2))
            {
                if (inscriptionVueModele.Utilisateur.Mdp == inscriptionVueModele.Mdp2)
                {
                    if (utilisateurService.CheckForDuplicatedEmail(inscriptionVueModele.Utilisateur.Email))
                    {
                        string mdp = Hashage.Sha256(inscriptionVueModele.Utilisateur.Mdp);
                        var utilisateur = new Utilisateur()
                        {
                            Nom = inscriptionVueModele.Utilisateur.Nom,
                            Prenom = inscriptionVueModele.Utilisateur.Prenom,
                            Email = inscriptionVueModele.Utilisateur.Email,
                            Mdp = mdp
                        };

                        utilisateurService.InsertUtilisateur(utilisateur);
                        utilisateurService.Save();
                        return Redirect("/Login/Login");
                    }
                }
            }  
            return View(inscriptionVueModele);
        }
    }
}

BackOffice/Controllers/PretsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Modeles;
using Repositories;
using Services.Service;

namespace BackOffice.Controllers
{
    [Authorize]
    public class PretsController : Controller
    {
        private ProjetContext context = new ProjetContext();
        private PretService pretService;

        public PretsController()
        {
            this.pretService = new PretService(this.context);
        }

        // GET: Prets
        public ActionResult Index()
        {
            return View(pretService.GetPrets());
        }

        // GET: Prets/Details/5
        public ActionResult Details(int id)
        {
            Pret pret = pretService.GetPretByID(id);
            if (pret == null)
            {
                return HttpNotFound();
            }
            return View(pret);
        }

        // GET: Prets/Create
        public ActionResult Create()
        {
            ViewBag.LivreID = new SelectList(context.Livres, "LivreID", "Titre");
            ViewBag.MembreID = new SelectList(context.Membres, "MembreID", "Nom");
            return View();
        }

        // POST: Prets/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PretID,Ddebut,Dfin,Dretour,MembreID,LivreID")] Pret pret)
        {
            if (ModelState.IsValid)
            {
                pretService.InsertPret(pret);
                pretService.Save();
                return RedirectToAction("Index");
            }

            ViewBag.LivreID = new SelectList(context.Livres, "LivreID", "Titre", pret.LivreID);
            ViewBag.MembreID = new SelectList(context.Membres, "MembreID", "Nom", pret.MembreID);
            return View(pret);
        }

        // GET: Prets/Edit/5
        public ActionResult Edit(int id)
        {
            Pret pret = pretService.GetPretByID(id);
            if (pret == null)
            {
                return HttpNotFound();
            }
            ViewBag.LivreID = new SelectList(context.Livres, "LivreID", "Titre", pret.LivreID);
            ViewBag.MembreID = new SelectList(context.Membres, "MembreID", "Nom", pret.MembreID);
            return View(pret);
        }

        // POST: Prets/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PretID,Ddebut,Dfin,Dretour,MembreID,LivreID")] Pret pret)
        {
            if (ModelState.IsValid)
            {
                pretService.UpdatePret(pret);
                //pretService.Save();
                return RedirectToAction("Index");
            }
            ViewBag.LivreID = new SelectList(context.Livres, "LivreID", "Titre", pret.LivreID);
            ViewBag.MembreID = new SelectList(context.Membres, "MembreID", "Nom", pret.MembreID);
            return View(pret);
        }

        // GET: Prets/Delete/5
        public ActionResult Delete(int id)
        {
            Pret pret = pretService.GetPretByID(id);
            if (pret == null)
            {
                return HttpNotFound();
            }
            return View(pret);
        }

        // POST: Prets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            pretService.DeletePret(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BackOffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        @Html.ActionLink("Booky", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            @if (User.Identity.IsAuthenticated)
            {
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Livres", "Index", "Livres", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Auteurs", "Index", "Auteurs", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Catégories", "Index", "Categories", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Prêts", "Index", "Prets", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Membres", "Index", "Membres", null, new { @class = "nav-link" })
                    </li>
                </ul>
                <ul class="navbar-nav my-2 my-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Se déconnecter", "Logout", "Login", null, new { @class = "nav-link" })
                    </li>
                </ul>
            }
            else
            {
                <ul class="navbar-nav mr-auto">
                </ul>
                <ul class="navbar-nav my-2 my-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Se connecter", "Login", "Login", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("S'inscrir", "Inscription", "Inscription", null, new { @class = "nav-link" })
                    </li>
                </ul>
            }
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>